name: integration
on:
  push:
  workflow_dispatch:
jobs:
  check-build-test:
    runs-on: gha-runner-scale-set
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Building TestProject1
        run: dotnet build

      - name: Running tests
        run: dotnet restore && dotnet test